### PR TITLE
Moves some apps into their own repos.

### PR DESCRIPTION
**Pull request by rolandpoulter**

### CODE REVIEW

**Comment by benbp** [comment]
Failed travis check, but +1 if you fix that.

**Comment by benbp** [comment]
Seems the travis check is ignorable since we're just testing it and missing .travis.yml?

**Comment by rolandpoulter** [comment]
@benbp I was going to see if I couldn't get it to run on travis. It can be merged now or later either way.

**Comment by tldavies** [comment]
test this please

**Comment by rolandpoulter** [comment]
test this please

**Comment by tldavies** [comment]
:+1:

**Comment by rolandpoulter** [comment]
@benbp can you merge please

**Comment by rolandpoulter** [comment]
test this please

**Pull request merged**
