### PR TITLE
Adjusted Workflows to Workflow History since it is more accurate

### PR DESCRIPTION
**Pull request by king-jam**

### CODE REVIEW

**Comment by heckj** [comment]
:+1:  on content update, presuming it fits with content/layout design

**Comment by heckj** [comment]
View of what this looks like: screen shot 2016-01-21 at 8 13 37 am

**Comment by rolandpoulter** [comment]
:+1:

**Comment by rolandpoulter** [comment]
@king-jam deployed to gh-pages. Thanks for the PR.

**Pull request merged**
